name: "Backend verify"

on:
  push:
    tags:
      - v*
    branches:
      - master
    paths:
      - 'backend/**.go'
  pull_request:
    paths:
      - 'backend/**.go'

permissions:
  contents: read

jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest-4
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'backend/go.mod'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          args: --timeout=5m
          working-directory: backend

      - name: test
        run: go test -v -race --tags=integration -p=1 ./...
        working-directory: backend
