name: "Backend verify"

on:
  push:
    tags:
      - v*
    branches:
      - master
    paths:
      - 'backend/**.go'
  pull_request:
    paths:
      - 'backend/**.go'

permissions:
  contents: read

jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          # go-version-file: 'backend/go.mod'
          # for now pin the verify action to 1.20.5
          # due to issue with testcontainers
          # https://github.com/golang/go/issues/61431
          # https://github.com/testcontainers/testcontainers-go/issues/1359
          go-version: '1.20.5'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          args: --timeout=5m
          working-directory: backend
    
      - name: test
        run: go test -race --tags=integration -p=1 ./...
        working-directory: backend
