name: snyk scanning

on:
  push:
    branches: ["master", "release-*"]

  workflow_dispatch:

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install snyk
        run: npm install -g snyk

      - name: install deps and scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk monitor --project-name=backend --remote-repo=redpanda-data/console-test --target-reference=${GITHUB_REF#refs/heads/} backend/
        shell: bash