name: "Backend unit tests"

on:
  push:
    tags:
      - v*
    branches:
      - master
    paths:
      - 'backend/**.go'
  pull_request:
    paths:
      - 'backend/**.go'

defaults:
  run:
    working-directory: backend

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Test with the Go CLI
        run: go test -race ./...