name: "Frontend Lint & Compile check"

on:
  push:
    paths:
      - "frontend/**"
  pull_request:
    paths:
      - "frontend/**"
jobs:
  lint-and-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.10.0'

      - name: Install dependencies 
        run: |
          cd frontend
          npm ci
      - name: Run lint
        run: |
          cd frontend
          npm run lint
      - name: Run build frontend
        run: |
          cd frontend
          REACT_APP_BUSINESS=true 
          REACT_APP_CONSOLE_GIT_SHA=$(echo $GITHUB_SHA | cut -c 1-6)
          REACT_APP_CONSOLE_GIT_REF=$GITHUB_REF_NAME 
          REACT_APP_BUILD_TIMESTAMP=$(date +%s) 
          REACT_APP_DEV_HINT=true
          npm run build 
  
  e2e-test:
    needs: "lint-and-compile"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.10.0'
      - name: Install dependencies 
        run: |
          cd frontend
          npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: |
          cd frontend
          npm run e2e-test
